workflows:
  ios-automatic-code-signing:
    name: iOS automatic code signing
    instance_type: mac_mini_m1
    working_directory: ios/ios-automatic-code-signing-demo-project
    environment:
      groups:
        - ios_creds # <-- (group contains variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY)
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # Based on your Flutter project
        XCODE_SCHEME: "Runner" # Based on your Flutter project
        BUNDLE_ID: "blue.pita.cooldowns" # Your app's bundle ID
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
      xcode: 14.3
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
    scripts:
      - name: Install pods
        script: pod install
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Build ipa for distribution
        working_directory: ios/ios-automatic-code-signing-demo-project
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#ce-builds"
        notify_on_build_start: true
        notify:
          success: false
          failure: false

  ios-manual-code-signing:
    name: iOS manual code signing
    instance_type: mac_mini_m1
    working_directory: ios/ios-manual-code-signing-demo-project
    environment:
      groups:
        - ios_manual_signing # <-- (group contains variables: CM_PROVISIONING_PROFILE, CM_CERTIFICATE)
        - ios_creds # <-- (group contains variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY)
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # Based on your Flutter project
        XCODE_SCHEME: "Runner" # Based on your Flutter project
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
    scripts:
      - name: Install pods
        script: pod install
      - name: Initialize keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: set up provisioning profiles
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${CM_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"
      - name: Add signing certificate to keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12
      - name: Increment build number
        script: agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build .ipa
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#ce-builds"
        notify_on_build_start: true
        notify:
          success: false
          failure: false
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  ios-code-signing-identities:
    name: iOS code signing identities
    integrations:
      app_store_connect: NC_API_KEY
    instance_type: mac_mini_m2
    working_directory: ios/ios-code-signing-identities-demo-project
    environment:
      ios_signing:
        provisioning_profiles:
          - swiftly-profile
        certificates:
          - ios-distribution
      groups:
        - ios_creds # <-- (group contains variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY)
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" # Based on your Flutter project
        XCODE_SCHEME: "Runner" # Based on your Flutter project
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
    scripts:
      - name: Install pods
        script: pod install
      - name: Increment build number
        script: agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build .ipa
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: "#ce-builds"
        notify_on_build_start: true
        notify:
          success: false
          failure: false
      app_store_connect:
        auth: integration

  flutter-yaml-ios:
    name: Flutter yaml iOS
    instance_type: mac_mini_m2
    working_directory: flutter/flutter-android-and-ios-yaml-demo-project
    max_build_duration: 120
    environment:
      groups:
        - ios_creds # <-- (group contains variables: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY)
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "blue.pita.cooldowns"
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
      flutter: stable
      xcode: 14.3
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter unit tests
        script: flutter test
        ignore_failure: true
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: false
      slack:
        channel: "#ce-builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false

  flutter-flavors-ios-dev:
    name: iOS Flutter Flavors Dev
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: flutter/flutter-flavors-demo-project
    environment:
      groups:
        - ios_creds
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
        XCODE_CONFIG: Release-dev
        XCODE_SCHEME: dev
        BUNDLE_ID: blue.pita.cooldowns.dev # Update for your app flavor
        ENTRY_POINT: lib/main_dev.dart
      flutter: stable
      xcode: 14.3
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Pod install
        script: find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist \
          --flavor="$XCODE_SCHEME" \
          -t "$ENTRY_POINT"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  flutter-flavors-ios-prod:
    name: iOS Flutter Flavors Prod
    instance_type: mac_mini_m2
    max_build_duration: 120
    working_directory: flutter/flutter-flavors-demo-project
    environment:
      groups:
        - ios_creds
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        APP_STORE_APP_ID: 6520381456 # Your App Store app ID
        XCODE_CONFIG: Release-prod
        XCODE_SCHEME: prod
        BUNDLE_ID: blue.pita.cooldowns.prod # Update for your app flavor
        ENTRY_POINT: lib/main_prod.dart
      flutter: stable
      xcode: 14.3
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script: flutter packages pub get
      - name: Pod install
        script: find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist \
          --flavor="$XCODE_SCHEME" \
          -t "$ENTRY_POINT"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - pita.sherwood@protonmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
