# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'shared_preferences', :path => '../.symlinks/plugins/shared_preferences/ios'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunnerUITests' do
    inherit! :search_paths
    # Pods for UI testing
  end
end
